### ISSUE TITLE
Wrong level colors?

### ISSUE THREAD

**Issue by GLodi** [javierugarte/GithubContributionsView#10]
Hi, 
I've just implemented this library in my app, but it appears that it's not working correctly. 
I think the contributions are downloaded correctly, but the "level" of each day is not recognised. I feel like that may have to do with the colors inside ContributionsProvider. Is it possible that GitHub's colors have been changed and therefore not recognised?

**Comment by GLodi** [comment]
In case you want to fix it, these are the new colors:

`
case "#ebedf0": level = 0; 
case "#c6e48b": level = 1; 
case "#7bc96f": level = 2; 
case "#239a3b": level = 3; 
case "#196127": level = 4; 
break;
`

**Comment by javierugarte** [comment]
Thanks you very much, I've just now released 1.2.2 version.

You can also contribute and send me PR :)

**Comment by GLodi** [comment]
Thank you for the release!
Totally forgot I could do that :P
